### ISSUE TITLE
1.9.12 fails to compile on mips

### ISSUE THREAD

**Issue by matoro** [sudo-project/sudo#189]
This appears to be caused by https://github.com/sudo-project/sudo/commit/3d995f7e58a38b42b41ba94026e2b7a3042d9df4

```
./exec_ptrace.c: In function ‘ptrace_getregs’:
./exec_ptrace.c:302:22: error: ‘iov’ undeclared (first use in this function)
  302 |             compat = iov.iov_len != sizeof(regs->u.native);
      |                      ^~~
./exec_ptrace.c:302:22: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:666: exec_ptrace.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Downstream bug:  https://bugs.gentoo.org/878401

**Comment by millert** [comment]
This should be fixed by 7944494196d4a9b33e0ae64a7e20f86e19c336d3

**Comment by matoro** [comment]
> This should be fixed by [7944494](https://github.com/sudo-project/sudo/commit/7944494196d4a9b33e0ae64a7e20f86e19c336d3)

Works for me, thanks!  :+1:
